# Generated by Django 3.1.1 on 2021-05-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210530_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(height_field=100, upload_to='images/', width_field=100),
        ),
    ]
